version: "3.9"

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: openguild
      POSTGRES_PASSWORD: openguild
      POSTGRES_DB: openguild
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    command: server /data
    environment:
      MINIO_ACCESS_KEY: openguild
      MINIO_SECRET_KEY: openguildsecret
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

  nats:
    image: nats:2
    command: ["-js"]
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - natsdata:/data

  server:
    build:
      context: ../backend
    environment:
      DATABASE_URL: postgres://openguild:openguild@postgres:5432/openguild
      OPENGUILD_SERVER__METRICS__ENABLED: "true"
      OPENGUILD_SERVER__METRICS__BIND_ADDR: "0.0.0.0:9100"
      MEDIA_ENDPOINT: http://minio:9000
      MEDIA_BUCKET: openguild
      MEDIA_ACCESS_KEY: openguild
      MEDIA_SECRET_KEY: openguildsecret
      NATS_URL: nats://nats:4222
    depends_on:
      - postgres
      - minio
      - nats
    ports:
      - "8080:8080"
      - "9100:9100"

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.listen-address=:9090"
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheusdata:/prometheus
    depends_on:
      - server
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss:10.4.3
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SERVER_ROOT_URL: http://localhost:3000
    volumes:
      - grafanadata:/var/lib/grafana
      - ./observability/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
    ports:
      - "3000:3000"

volumes:
  pgdata:
  miniodata:
  natsdata:
  prometheusdata:
  grafanadata:
