[package]
name = "openguild-media"
version = "0.0.1"
edition = "2021"
description = "Media repository integrations for OpenGuild"
license = "AGPL-3.0-or-later"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
config = "0.14"
