apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: PBFAFD06EF2E8156
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 15s
    version: 1
    editable: false
